Добавлена область с сообщениями
MoreliaTalk/morelia_client_flutter pull request #39
Opened 2022-03-05 14:27 UTC by NekrodNIK

Изменения:
-
- добавлена область сообщениями
- выполнен переход на библиотеку управления состоянием riverpod
- изменена структура каталогов, главный экран вынесен в main_screen.dart
- тема приложения вынесена в отдельное состояние
- добавлена поддержка android
- другие мелкие, но важные изменения

2022-03-05 15:12 UTC, rus-ai requested changes

2022-03-05 15:12 UTC, rus-ai commented on lib/components/message_area.dart
> +      state = [
А почему не  .add()? Это же просто список, не виджет он вполне mutatable

2022-03-05 15:12 UTC, rus-ai commented on lib/components/message_area.dart
> +              style: TextStyle(color: textColor),
Я бы весь testStyle раньше в константу загонял, а не только цвет. Опять таки в расчёте на будущие сообщения типа "service_message" они скорее всего и размером шрифта могут отличаться. Но тут спорное пожелание.

2022-03-05 15:12 UTC, rus-ai commented on lib/screens/main_screen.dart
> +    } else {
А web как же? Или платформа для них работает?

2022-03-05 15:12 UTC, rus-ai commented on lib/screens/main_screen.dart
> +    } else if (isDesktopDevice) {
Не сейчас, но в будущем надо будет сюда же и планшеты задать, надо только придумать как их отличать

2022-03-05 15:12 UTC, rus-ai commented on test/widget_test.dart
> -
Может вообще тестовый файл пока грохнуть чтобы flutter test не ругался?

2022-03-05 15:25 UTC, NekrodNIK commented on android/app/src/debug/AndroidManifest.xml
> +    package="com.example.morelia_client_flutter">
ладно, это просто flutter сгенерил

2022-03-05 15:31 UTC, NekrodNIK commented on android/app/src/debug/AndroidManifest.xml
> +    package="com.example.morelia_client_flutter">
Готово

2022-03-05 15:32 UTC, NekrodNIK commented on lib/components/message_area.dart
> +    if (this.type == "my") {
ок

2022-03-05 15:44 UTC, NekrodNIK commented on lib/components/message_area.dart
> +    if (this.type == "my") {
Готово

2022-03-05 15:45 UTC, NekrodNIK commented on lib/components/message_area.dart
> +          bottomRight: Radius.circular(3));
нет, смотрится уродливо. Лучше чуть закруглить и всё

2022-03-05 15:46 UTC, NekrodNIK commented on lib/components/message_area.dart
> +      state = [
Нет. Это StateNotiferProvider, а в нём как раз всё не mutable

2022-03-05 15:48 UTC, NekrodNIK commented on lib/components/message_area.dart
> +      state = [
Provider Type | Provider Create Function | Example Use Case
-- | -- | --
Provider | Returns any type | A service class / computed property (filtered list)
StateProvider | Returns any type | A filter condition / simple state object
FutureProvider | Returns a Future of any type | A result from an API call
StreamProvider | Returns a Stream of any type | A stream of results from an API
StateNotifierProvider | Returns a subclass of StateNotifier | A complex state object that is immutable except through an interface
ChangeNotifierProvider | Returns a subclass of ChangeNotifier | A complex state object that requires mutability

[Provider](https://riverpod.dev/docs/providers/provider) Type	Provider Create Function	Example Use Case
Provider	Returns any type	A service class / computed property (filtered list)
[StateProvider](https://riverpod.dev/docs/providers/state_provider)	Returns any type	A filter condition / simple state object
[FutureProvider](https://riverpod.dev/docs/providers/future_provider)	Returns a Future of any type	A result from an API call
[StreamProvider](https://riverpod.dev/docs/providers/stream_provider)	Returns a Stream of any type	A stream of results from an API
[StateNotifierProvider](https://riverpod.dev/docs/providers/state_notifier_provider)	Returns a subclass of StateNotifier	A complex state object that is immutable except through an interface
[ChangeNotifierProvider](https://pub.dev/documentation/flutter_riverpod/latest/flutter_riverpod/ChangeNotifierProvider-class.html)	Returns a subclass of ChangeNotifier	A complex state object that requires mutability

2022-03-05 15:49 UTC, NekrodNIK commented on lib/components/message_area.dart
> +              style: TextStyle(color: textColor),
Пока не критично. Потом посмотрим.

2022-03-05 15:52 UTC, NekrodNIK commented on test/widget_test.dart
> -
Ладно

2022-03-05 15:53 UTC, NekrodNIK commented on test/widget_test.dart
> -
Готово

2022-03-05 15:53 UTC, NekrodNIK commented on lib/screens/main_screen.dart
> +    } else if (isDesktopDevice) {
Ну это да

2022-03-05 15:54 UTC, NekrodNIK commented on lib/screens/main_screen.dart
> +    } else {
Пока нет, надо как-то определять платформу в вебе, но пока не заморачивался

2022-03-05 17:34 UTC, rus-ai approved these changes

2022-03-06 04:58 UTC, stepanskryabin approved these changes

2022-03-06 05:25 UTC, merged